### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by jmague** [ricklupton/ipython-d3-sankey#1]
The command   `sudo pip install ipython-d3-sankey`failed with the following error:

```
Command python setup.py egg_info failed with error code 1 in /private/tmp/pip_build_root/ipython-d3-sankey
Storing debug log for failure in /Users/jmague/.pip/pip.log
```

Here is the log: 

```
Downloading/unpacking ipython-d3-sankey
  Getting page https://pypi.python.org/simple/ipython-d3-sankey/
  URLs to search for versions for ipython-d3-sankey:
  * https://pypi.python.org/simple/ipython-d3-sankey/
  Analyzing links from page https://pypi.python.org/simple/ipython-d3-sankey/
    Found link https://pypi.python.org/packages/source/i/ipython-d3-sankey/ipython-d3-sankey-0.1.0.tar.gz#md5=1d3604c2d360bfc16c0b70890507cebe (from https://pypi.python.org/simple/ipython-d3-sankey/), version: 0.1.0
    Found link https://pypi.python.org/packages/source/i/ipython-d3-sankey/ipython-d3-sankey-0.1.1.tar.gz#md5=5c4c4d7a34844d1303c8417a75fa944d (from https://pypi.python.org/simple/ipython-d3-sankey/), version: 0.1.1
  Using version 0.1.1 (newest of versions: 0.1.1, 0.1.0)
  Downloading from URL https://pypi.python.org/packages/source/i/ipython-d3-sankey/ipython-d3-sankey-0.1.1.tar.gz#md5=5c4c4d7a34844d1303c8417a75fa944d (from https://pypi.python.org/simple/ipython-d3-sankey/)
  Running setup.py (path:/private/tmp/pip_build_root/ipython-d3-sankey/setup.py) egg_info for package ipython-d3-sankey
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/private/tmp/pip_build_root/ipython-d3-sankey/setup.py", line 32, in <module>
        'ipythond3sankey.widgets']),
    TypeError: find_packages() got an unexpected keyword argument 'include'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/private/tmp/pip_build_root/ipython-d3-sankey/setup.py", line 32, in <module>

    'ipythond3sankey.widgets']),

TypeError: find_packages() got an unexpected keyword argument 'include'

----------------------------------------
Cleaning up...
  Removing temporary dir /private/tmp/pip_build_root...
Command python setup.py egg_info failed with error code 1 in /private/tmp/pip_build_root/ipython-d3-sankey
Exception information:
Traceback (most recent call last):
  File "/Users/jmague/anaconda/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/Users/jmague/anaconda/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/Users/jmague/anaconda/lib/python2.7/site-packages/pip/req.py", line 1229, in prepare_files
    req_to_install.run_egg_info()
  File "/Users/jmague/anaconda/lib/python2.7/site-packages/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/Users/jmague/anaconda/lib/python2.7/site-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /private/tmp/pip_build_root/ipython-d3-sankey
```

I'm using Python 2.7.10 form anaconda and pip 1.5.6

```
$ pip --version
pip 1.5.6 from /Users/jmague/anaconda/lib/python2.7/site-packages (python 2.7)
$ python --version
Python 2.7.10 :: Anaconda 2.0.1 (x86_64)
```

**Comment by ricklupton** [comment]
Hi,

I think you have an old version of setuptools. Can you try

``` console
$ sudo pip install --upgrade setuptools
$ sudo pip install ipython-d3-sankey
```

I'll see if I can update this package to automatically require an up to date version of setuptools, but in the meantime I think that should work.

**Comment by jmague** [comment]
That was it! Thanks
